"""
Contradiction Engine - Emergent pressure from belief conflicts.

Stage: Cognitive Architecture

Contradiction detection is the core of "real thinking".
Not synthetic pressure, but emergent cognitive tension.

When beliefs conflict, pressure emerges naturally:
- goal A conflicts with goal B
- belief X conflicts with evidence Y
- identity wants safety but planner wants exploration

This engine:
1. Detects contradictions in beliefs/goals/identity
2. Computes pressure intensity
3. Routes pressure to appropriate cognitive systems
4. Triggers resolution strategies
"""
from types import MappingProxyType
from typing import Dict, Any, Optional, Tuple, List, Set, FrozenSet
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
import hashlib
import json


class ContradictionType(Enum):
    """Types of cognitive contradictions"""
    BELIEF_BELIEF = "belief_belief"  # Two beliefs contradict
    BELIEF_GOAL = "belief_goal"  # Belief conflicts with goal
    GOAL_GOAL = "goal_goal"  # Two goals conflict
    IDENTITY_STRATEGY = "identity_strategy"  # Strategy contradicts identity
    EVIDENCE_BELIEF = "evidence_belief"  # New evidence contradicts belief
    VALUE_VALUE = "value_value"  # Two values conflict
    CAUSAL_CYCLE = "causal_cycle"  # Circular causality detected


class PressureType(Enum):
    """Type of cognitive pressure"""
    COGNITIVE = "cognitive"  # Mental load
    EMOTIONAL = "emotional"  # Affective tension
    EXISTENTIAL = "existential"  # Identity threat
    PRACTICAL = "practical"  # Execution conflict
    TEMPORAL = "temporal"  # Time pressure


@dataclass(frozen=True)
class Contradiction:
    """
    A detected cognitive contradiction.
    
    Contains:
    - type: what kind of contradiction
    - participants: what's in conflict
    - intensity: how strong the contradiction is (0-1)
    - resolution_state: is it resolved, pending, or escalating
    """
    contradiction_id: str
    type: str  # ContradictionType value
    participants: FrozenSet[str]  # IDs of conflicting elements
    description: str  # Human-readable description
    intensity: float  # 0-1, how strong
    detected_at: str
    resolution_state: str  # "unresolved", "acknowledged", "resolved", "escalated"
    evidence: Tuple[str, ...]  # What evidence this contradiction
    resolution_attempts: Tuple[str, ...]  # Resolution attempt IDs
    
    def is_escalated(self) -> bool:
        return self.resolution_state == "escalated"
    
    def is_resolved(self) -> bool:
        return self.resolution_state == "resolved"
    
    def is_pending(self) -> bool:
        return self.resolution_state in ("unresolved", "acknowledged")


@dataclass(frozen=True)
class Pressure:
    """
    Cognitive pressure generated by contradictions.
    
    Pressure emerges from unresolved contradictions.
    The longer unresolved, the higher the pressure.
    """
    pressure_id: str
    source_contradiction_id: str  # What contradiction generated this
    type: str  # PressureType value
    intensity: float  # 0-1, how much pressure
    components: FrozenSet[str]  # What's under pressure (cognitive systems)
    accumulated_at: str
    decay_rate: float  # How fast pressure naturally decays
    urgency: float  # 0-1, how urgent to resolve
    
    def is_urgent(self) -> bool:
        return self.urgency >= 0.7
    
    def is_critical(self) -> bool:
        return self.intensity >= 0.9 or self.urgency >= 0.9


@dataclass(frozen=True)
class ResolutionAttempt:
    """
    An attempt to resolve a contradiction.
    
    Records what was tried, what worked, what didn't.
    """
    attempt_id: str
    contradiction_id: str
    strategy: str  # What resolution strategy was used
    outcome: str  # "succeeded", "failed", "partial"
    effects: Tuple[str, ...]  # What beliefs/goals were modified
    timestamp: str
    lessons_learned: Tuple[str, ...]
    
    def succeeded(self) -> bool:
        return self.outcome == "succeeded"
    
    def failed(self) -> bool:
        return self.outcome == "failed"


@dataclass(frozen=True)
class ContradictionState:
    """
    State of the contradiction engine.
    
    Tracks all contradictions, pressures, and resolution attempts.
    """
    contradictions: MappingProxyType  # type: ignore
    pressures: MappingProxyType  # type: ignore
    resolution_attempts: MappingProxyType  # type: ignore
    total_pressure: float  # Sum of all active pressure
    unresolved_count: int
    escalated_count: int
    version: int
    
    def __post_init__(self):
        for attr in ('contradictions', 'pressures', 'resolution_attempts'):
            val = getattr(self, attr)
            if not isinstance(val, MappingProxyType):
                object.__setattr__(self, attr, MappingProxyType(dict(val)))
    
    @staticmethod
    def compute_total_pressure(state: 'ContradictionState') -> float:
        return sum(p.intensity for p in state.pressures.values())
    
    @staticmethod
    def compute_hash(state: 'ContradictionState') -> str:
        data = {
            "version": state.version,
            "contradiction_count": len(state.contradictions),
            "pressure_count": len(state.pressures),
            "total_pressure": state.total_pressure,
            "unresolved_count": state.unresolved_count,
            "escalated_count": state.escalated_count
        }
        return hashlib.sha256(
            json.dumps(data, sort_keys=True).encode()
        ).hexdigest()
    
    def get_active_pressures(self) -> List[Pressure]:
        return [p for p in self.pressures.values() if p.intensity > 0.1]
    
    def get_escalated(self) -> List[Contradiction]:
        return [c for c in self.contradictions.values() if c.is_escalated()]
    
    def get_unresolved(self) -> List[Contradiction]:
        return [c for c in self.contradictions.values() if c.is_pending()]


def create_empty_contradiction_state() -> ContradictionState:
    """Create initial empty contradiction state"""
    return ContradictionState(
        contradictions=MappingProxyType({}),
        pressures=MappingProxyType({}),
        resolution_attempts=MappingProxyType({}),
        total_pressure=0.0,
        unresolved_count=0,
        escalated_count=0,
        version=0
    )


# Detection logic

def detect_belief_belief_conflict(
    belief1_id: str,
    belief1_confidence: float,
    belief2_id: str,
    belief2_confidence: float,
    mutual_exclusion: bool = True
) -> Optional[float]:
    """
    Detect conflict between two beliefs.
    
    Returns intensity (0-1) if conflict detected, None otherwise.
    
    Factors:
    - Confidence levels (high confidence + high confidence = strong conflict)
    - Mutual exclusion (are they logically contradictory?)
    """
    if not mutual_exclusion:
        return None
    
    # Both high confidence = strong potential conflict
    intensity = (belief1_confidence + belief2_confidence) / 2
    
    if intensity >= 0.6:
        return intensity
    
    return None


def detect_goal_goal_conflict(
    goal1_priority: float,
    goal2_priority: float,
    goal1_resources: float,
    goal2_resources: float,
    resource_overlap: bool = True
) -> Optional[float]:
    """
    Detect conflict between two goals.
    
    Returns intensity (0-1) if conflict detected.
    """
    if not resource_overlap:
        return None
    
    # Both high priority + competing resources = conflict
    intensity = (goal1_priority + goal2_priority) / 2
    resource_pressure = min(goal1_resources, goal2_resources)
    
    return intensity * (1 + resource_pressure) / 2


def detect_evidence_belief_conflict(
    belief_confidence: float,
    evidence_strength: float,
    evidence_direction: float  # -1 to 1, negative to positive for belief
) -> Optional[float]:
    """
    Detect when new evidence contradicts existing belief.
    
    Returns intensity (0-1) of conflict.
    """
    # Evidence points opposite to belief direction
    expected_direction = 1 if belief_confidence > 0.5 else -1
    
    if expected_direction * evidence_direction < 0:
        # Evidence contradicts belief direction
        intensity = abs(evidence_strength - belief_confidence) / 2
        return min(1.0, intensity)
    
    return None


def compute_pressure_intensity(
    contradiction: Contradiction,
    age_hours: float,
    resolution_attempts: int
) -> float:
    """
    Compute pressure intensity from contradiction.
    
    Factors:
    - Base intensity from contradiction
    - Age (older = more pressure)
    - Failed attempts = more pressure
    """
    base = contradiction.intensity
    
    # Age factor (logarithmic growth, max 2x after 24 hours)
    age_factor = 1.0 + min(1.0, age_hours / 24)
    
    # Attempt factor (failed attempts increase pressure)
    attempt_factor = 1.0 + resolution_attempts * 0.2
    
    intensity = base * age_factor * attempt_factor
    
    return min(1.0, intensity)


def determine_pressure_type(contradiction_type: str) -> str:
    """Map contradiction type to pressure type"""
    mapping = {
        ContradictionType.BELIEF_BELIEF.value: PressureType.COGNITIVE.value,
        ContradictionType.BELIEF_GOAL.value: PressureType.COGNITIVE.value,
        ContradictionType.GOAL_GOAL.value: PressureType.PRACTICAL.value,
        ContradictionType.IDENTITY_STRATEGY.value: PressureType.EXISTENTIAL.value,
        ContradictionType.EVIDENCE_BELIEF.value: PressureType.COGNITIVE.value,
        ContradictionType.VALUE_VALUE.value: PressureType.EMOTIONAL.value,
        ContradictionType.CAUSAL_CYCLE.value: PressureType.COGNITIVE.value,
    }
    return mapping.get(contradiction_type, PressureType.COGNITIVE.value)


def select_resolution_strategy(
    contradiction_type: str,
    intensity: float,
    previous_attempts: List[ResolutionAttempt]
) -> str:
    """
    Select appropriate resolution strategy based on:
    - Type of contradiction
    - Intensity
    - History of previous attempts
    """
    if previous_attempts:
        last_outcome = previous_attempts[-1].outcome
        if last_outcome == "failed":
            # Try different approach
            if intensity < 0.5:
                return "accept_diversity"  # Accept both and coexist
            else:
                return "seek_mediation"  # Find compromise
    
    # Default strategies by type
    strategies = {
        ContradictionType.BELIEF_BELIEF.value: "evidence_evaluation",
        ContradictionType.GOAL_GOAL.value: "prioritization",
        ContradictionType.EVIDENCE_BELIEF.value: "belief_revision",
        ContradictionType.IDENTITY_STRATEGY.value: "identity_reconciliation",
        ContradictionType.VALUE_VALUE.value: "value_weighing",
    }
    
    return strategies.get(contradiction_type, "general_negotiation")