"""
Phase 36 — Execution-Consistent Behavioral Physics Learning

CLOSES THE LOOP:
  flow policy → trajectory → world model update →
  inverse dynamics update → manifold reorganization → better flows

KEY INSIGHT:
  Before Phase 35, world model training was meaningless because
  trajectories were random (no persistent control dynamics).
  
  Now trajectories are generated by structured flows.
  World model FINALLY has real behavioral physics to learn.

WHAT CHANGES:
  1. Flow-conditioned dynamics: P(z_{t+1} | z_t, h_t, a_t, π)
     Different flow regimes → different learned dynamics
  
  2. Multi-step sequence training on flow-generated trajectories
     k-step consistency: z_pred(t:t+k) ≈ z_actual(t:t+k)
  
  3. Interleaved execution + training
     execute → collect → train → improve → execute

  4. Validation: does world model improve on held-out flow trajectories?
     Metric: prediction error before/after training on flow data

ARCHITECTURE:
  Phase 35 Flow Engine
       ↓
  FlowTrajectoryBuffer (episodes with flow metadata)
       ↓
  FlowConditionedWorldModel (learns per-flow dynamics)
       ↓
  Multi-step sequence training (k-step consistency)
       ↓
  Inverse dynamics update (on real transitions)
       ↓
  Manifold reorganization (controllability-weighted)
       ↓
  Phase 35 Flow Engine (improved)
"""

import numpy as np
import random
from typing import List, Dict, Tuple, Optional, Any
from dataclasses import dataclass, field
from collections import defaultdict

from phase30_training_loop import MinimalWorldModel, TrajectoryBuffer, compute_sequence_loss
from phase31_hierarchical_execution import GoalAttractor
from phase32_skill_dynamics_coupling import ProbabilisticGoalEvaluator
from phase34_inverse_control_stabilization import InverseDynamicsModel
from phase35_dynamical_skill_flows import (
    SkillFlow, PointFlow, LimitCycleFlow, ComposedFlow,
    FlowManifold, rollout_flow, FlowCEM, DynamicalSkillEngine
)


# ============================================================================
# 1. FLOW-CONDITIONED WORLD MODEL
# ============================================================================

class FlowConditionedWorldModel(MinimalWorldModel):
    """
    World model that conditions on active flow regime.
    
    Standard:   P(z_{t+1} | z_t, h_t, a_t)
    Extended:   P(z_{t+1} | z_t, h_t, a_t, π_embedding)
    
    π_embedding encodes the active flow's dynamical signature.
    This lets the model learn that different flow regimes
    produce different dynamics.
    """
    
    def __init__(self, event_dim: int = 32, latent_dim: int = 16,
                 belief_dim: int = 64, action_dim: int = 16,
                 flow_embed_dim: int = 8):
        super().__init__(event_dim, latent_dim, belief_dim, action_dim)
        
        self.flow_embed_dim = flow_embed_dim
        
        # Extended transition model with flow conditioning
        trans_input = latent_dim + belief_dim + action_dim + flow_embed_dim
        scale = 0.1
        
        # Re-initialize transition with flow conditioning
        self.W_t1 = np.random.randn(64, trans_input) * scale
        self.b_t1 = np.zeros(64)
        self.W_t2 = np.random.randn(latent_dim, 64) * scale
        self.b_t2 = np.zeros(latent_dim)
        self.W_t_logvar = np.random.randn(latent_dim, 64) * scale * 0.5
        self.b_t_logvar = np.zeros(latent_dim) - 1.0
    
    def predict_transition(
        self, z: np.ndarray, h: np.ndarray, a: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Override: predict with zero flow embedding (default/unknown flow).
        Ensures downstream code (rollout_flow, CEM) works without change.
        """
        flow_embed = np.zeros(self.flow_embed_dim)
        return self.predict_transition_flow(z, h, a, flow_embed)

    def predict_transition_flow(
        self, z: np.ndarray, h: np.ndarray,
        a: np.ndarray, flow_embed: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Predict next latent conditioned on flow.
        
        P(z_{t+1} | z_t, h_t, a_t, π)
        """
        z = np.asarray(z).flatten()[:self.latent_dim]
        h = np.asarray(h).flatten()[:self.belief_dim]
        a = np.asarray(a).flatten()[:self.action_dim]
        flow_embed = np.asarray(flow_embed).flatten()[:self.flow_embed_dim]
        
        if len(a) < self.action_dim:
            a = np.pad(a, (0, self.action_dim - len(a)))
        if len(flow_embed) < self.flow_embed_dim:
            flow_embed = np.pad(flow_embed, (0, self.flow_embed_dim - len(flow_embed)))
        
        x = np.concatenate([z, h, a, flow_embed])
        
        hidden = np.tanh(self.W_t1 @ x + self.b_t1)
        mu = self.W_t2 @ hidden + self.b_t2
        logvar = self.W_t_logvar @ hidden + self.b_t_logvar
        
        return mu, logvar
    
    def compute_flow_embedding(self, flow: SkillFlow) -> np.ndarray:
        """
        Encode flow into a fixed embedding vector.
        
        Captures the dynamical signature of the flow:
          - flow type
          - key parameters
          - stability
        """
        params = flow.get_parameters()
        
        # Normalize to flow_embed_dim
        embed = np.zeros(self.flow_embed_dim)
        
        # Type encoding
        type_code = {
            'point_attractor': np.array([1.0, 0.0, 0.0, 0.0]),
            'limit_cycle': np.array([0.0, 1.0, 0.0, 0.0]),
            'linear_flow': np.array([0.0, 0.0, 1.0, 0.0]),
            'composed_flow': np.array([0.0, 0.0, 0.0, 1.0]),
        }
        type_vec = type_code.get(flow.flow_type.value, np.zeros(4))
        
        # Stability
        stab_vec = np.array([flow.stability, flow.goal_alignment])
        
        # Parameter stats (mean, std)
        param_mean = float(np.mean(params))
        param_std = float(np.std(params)) if len(params) > 1 else 0.0
        
        combined = np.concatenate([type_vec, stab_vec, [param_mean, param_std]])
        
        embed[:len(combined)] = combined[:self.flow_embed_dim]
        return embed
    
    def rollout_sequence_flow(
        self, x_seq: List[np.ndarray], a_seq: List[np.ndarray],
        flow_embeds: List[np.ndarray], sample: bool = True
    ) -> Dict:
        """Rollout with flow conditioning."""
        h = np.zeros(self.belief_dim)
        
        mus = []
        logvars = []
        beliefs = []
        
        for t in range(len(x_seq)):
            h = self.gru_step(h, x_seq[t])
            z, mu, logvar = self.encode_latent(h, sample=sample)
            
            mus.append(mu)
            logvars.append(logvar)
            beliefs.append(h.copy())
        
        return {
            'mus': mus,
            'logvars': logvars,
            'beliefs': beliefs
        }


# ============================================================================
# 2. FLOW TRAJECTORY BUFFER
# ============================================================================

@dataclass
class FlowEpisode:
    """Complete trajectory episode with flow metadata."""
    states: List[np.ndarray]       # Latent states z_t
    beliefs: List[np.ndarray]      # Belief states h_t
    actions: List[np.ndarray]      # Actions a_t
    flow_embeddings: List[np.ndarray]  # Flow embeddings π_t
    rewards: List[float]           # Rewards r_t
    flow_ids: List[str]            # Which flows were active
    flow_types: List[str]          # Flow type names
    goal_id: str = ""              # Goal context
    goal_embedding: Optional[np.ndarray] = None
    timestamp: float = 0.0
    
    @property
    def length(self) -> int:
        return len(self.states)


class FlowTrajectoryBuffer:
    """
    Stores trajectory episodes generated by skill flows.
    
    Key difference from Phase 30 buffer:
      - Stores flow metadata (flow type, embedding, active flow)
      - Enables flow-conditioned training
      - Tracks which flow regime generated each transition
    """
    
    def __init__(self, max_episodes: int = 200):
        self.episodes: List[FlowEpisode] = []
        self.max_episodes = max_episodes
        self.total_transitions = 0
        
        # Per-flow statistics
        self.flow_stats: Dict[str, Dict] = defaultdict(lambda: {
            'n_transitions': 0,
            'total_reward': 0.0,
            'avg_uncertainty': 0.0
        })
    
    def add_episode(self, episode: FlowEpisode):
        """Add flow-generated episode."""
        self.episodes.append(episode)
        self.total_transitions += episode.length
        
        # Update per-flow stats
        for fid in set(episode.flow_ids):
            self.flow_stats[fid]['n_transitions'] += 1
        
        # Keep buffer bounded
        if len(self.episodes) > self.max_episodes:
            self.episodes = self.episodes[-self.max_episodes:]
    
    def add_from_execution(
        self,
        states: List[np.ndarray],
        beliefs: List[np.ndarray],
        actions: List[np.ndarray],
        flows: List[SkillFlow],
        rewards: Optional[List[float]] = None,
        goal: Optional[GoalAttractor] = None
    ):
        """Add episode from execution engine."""
        if rewards is None:
            rewards = [0.0] * len(states)
        
        flow_embeddings = [f.compute_flow_embedding(f) if hasattr(f, 'compute_flow_embedding') 
                          else np.zeros(8) for f in flows]
        flow_ids = [f.flow_id for f in flows]
        flow_types = [f.flow_type.value for f in flows]
        
        # Actually, flow embedding needs FlowConditionedWorldModel
        # Let's store raw flows for later embedding computation
        episode = FlowEpisode(
            states=[s.copy() for s in states],
            beliefs=[b.copy() for b in beliefs],
            actions=[a.copy() for a in actions],
            flow_embeddings=flow_embeddings,
            rewards=rewards,
            flow_ids=flow_ids,
            flow_types=flow_types,
            goal_id=goal.goal_id if goal else "",
            goal_embedding=goal.attractor_state.copy() if goal else None
        )
        
        self.add_episode(episode)
    
    def sample_batch(self, batch_size: int = 16,
                     seq_len: int = 10) -> List[Dict]:
        """
        Sample batch of sequences with flow conditioning.
        
        Returns: list of {x_seq, a_seq, r_seq, flow_embeds, flow_ids}
        """
        if not self.episodes:
            return []
        
        batch = []
        for _ in range(batch_size):
            ep = random.choice(self.episodes)
            
            if ep.length <= seq_len:
                batch.append({
                    'x_seq': ep.states,
                    'a_seq': ep.actions,
                    'r_seq': ep.rewards,
                    'flow_embeds': ep.flow_embeddings,
                    'flow_ids': ep.flow_ids
                })
                continue
            
            start = random.randint(0, ep.length - seq_len - 1)
            batch.append({
                'x_seq': ep.states[start:start + seq_len],
                'a_seq': ep.actions[start:start + seq_len],
                'r_seq': ep.rewards[start:start + seq_len],
                'flow_embeds': ep.flow_embeddings[start:start + seq_len],
                'flow_ids': ep.flow_ids[start:start + seq_len]
            })
        
        return batch
    
    def get_flow_distribution(self) -> Dict:
        """Get distribution of flows in buffer."""
        flow_counts = defaultdict(int)
        for ep in self.episodes:
            for fid in set(ep.flow_ids):
                flow_counts[fid] += 1
        return dict(flow_counts)
    
    def get_stats(self) -> Dict:
        """Buffer statistics."""
        if not self.episodes:
            return {'n_episodes': 0, 'n_transitions': 0}
        
        lengths = [ep.length for ep in self.episodes]
        return {
            'n_episodes': len(self.episodes),
            'n_transitions': self.total_transitions,
            'avg_length': float(np.mean(lengths)),
            'n_flow_types': len(self.get_flow_distribution())
        }


# ============================================================================
# 3. FLOW-CONDITIONED SEQUENCE LOSS
# ============================================================================

def compute_flow_sequence_loss(
    model: FlowConditionedWorldModel,
    batch: List[Dict],
    k_steps: int = 5
) -> float:
    """
    Multi-step sequence loss with flow conditioning.
    
    For each timestep t:
      1. Encode observation → z_t
      2. Predict k steps using flow-conditioned transition
      3. Compare with actual encoded latents
    
    This teaches the model that dynamics depend on active flow.
    """
    total_loss = 0.0
    n_samples = 0
    
    for sample in batch:
        x_seq = sample['x_seq']
        a_seq = sample['a_seq']
        flow_embeds = sample.get('flow_embeds', [None] * len(x_seq))
        
        seq_len = len(x_seq)
        if seq_len < k_steps + 2:
            continue
        
        # Full forward pass to get true latents
        h = np.zeros(model.belief_dim)
        true_mus = []
        beliefs = []
        
        for t in range(seq_len):
            h = model.gru_step(h, x_seq[t])
            _, mu, _ = model.encode_latent(h, sample=False)
            true_mus.append(mu)
            beliefs.append(h.copy())
        
        # Multi-step prediction loss
        for t in range(seq_len - k_steps):
            z_t = true_mus[t]
            h_t = beliefs[t]
            
            z_pred = z_t.copy()
            h_pred = h_t.copy()
            
            for i in range(k_steps):
                a = a_seq[t + i]
                
                # Get flow embedding at this step
                if flow_embeds[t + i] is not None:
                    flow_embed = flow_embeds[t + i]
                else:
                    flow_embed = np.zeros(model.flow_embed_dim)
                
                # Flow-conditioned prediction
                mu_pred, logvar_pred = model.predict_transition_flow(
                    z_pred, h_pred, a, flow_embed
                )
                
                z_true = true_mus[t + i + 1]
                
                loss_step = np.mean((mu_pred - z_true) ** 2)
                loss_unc = np.mean(np.exp(logvar_pred))
                
                total_loss += loss_step + 0.01 * loss_unc
                n_samples += 1
                
                z_pred = mu_pred
                h_pred = model.gru_step(h_pred, mu_pred)
    
    return total_loss / max(1, n_samples)


def compute_flow_reward_loss(
    model: FlowConditionedWorldModel,
    batch: List[Dict]
) -> float:
    """Reward prediction loss for flow-conditioned training."""
    total_loss = 0.0
    n_samples = 0
    
    for sample in batch:
        x_seq = sample['x_seq']
        r_seq = sample['r_seq']
        
        h = np.zeros(model.belief_dim)
        
        for t in range(len(x_seq)):
            h = model.gru_step(h, x_seq[t])
            z, _, _ = model.encode_latent(h, sample=False)
            
            r_pred = model.predict_reward(z, h)
            r_true = r_seq[t]
            
            total_loss += (r_pred - r_true) ** 2
            n_samples += 1
    
    return total_loss / max(1, n_samples)


# ============================================================================
# 4. CLOSED-LOOP TRAINING
# ============================================================================

class BehavioralPhysicsLearner:
    """
    Manages the closed-loop training process.
    
    Loop:
      Phase 35 engine → execute → collect trajectories →
      train world model → train inverse dynamics →
      reorganize manifold → Phase 35 engine (improved)
    
    Validation:
      Before/after training: does prediction error on
      held-out flow trajectories decrease?
    """
    
    def __init__(
        self,
        world_model: FlowConditionedWorldModel,
        inv_dyn: InverseDynamicsModel,
        manifold: FlowManifold,
        goal: GoalAttractor,
        learning_rate: float = 0.01,
        k_steps: int = 5,
        batch_size: int = 16,
        seq_len: int = 10
    ):
        self.wm = world_model
        self.inv_dyn = inv_dyn
        self.manifold = manifold
        self.goal = goal
        self.lr = learning_rate
        self.k_steps = k_steps
        self.batch_size = batch_size
        self.seq_len = seq_len
        
        # Experience buffer
        self.buffer = FlowTrajectoryBuffer(max_episodes=200)
        
        # Training state
        self.training_step = 0
        self.loss_history: List[float] = []
        self.val_history: List[float] = []
        
        # Validation episodes (held out)
        self.val_episodes: List[FlowEpisode] = []
    
    def record_episode(self, episode: FlowEpisode):
        """Record episode and optionally reserve for validation."""
        if len(self.val_episodes) < 10 and random.random() < 0.2:
            self.val_episodes.append(episode)
        else:
            self.buffer.add_episode(episode)
    
    def record_from_engine(
        self,
        engine_log: List[Dict],
        flows_used: List[SkillFlow],
        states: List[np.ndarray],
        beliefs: List[np.ndarray]
    ):
        """Record episode from DynamicalSkillEngine execution."""
        if not engine_log:
            return
        
        actions = []
        rewards = []
        step_flows = []
        
        for entry in engine_log:
            a = entry.get('action', np.zeros(self.wm.action_dim))
            r = entry.get('goal_prob', 0.0)
            actions.append(a)
            rewards.append(r)
            
            # Find the flow that generated this action
            flow_id = entry.get('flow_id', '')
            flow = self.manifold.flows.get(flow_id)
            if flow is None and self.manifold.flows:
                flow = list(self.manifold.flows.values())[0]
            step_flows.append(flow or PointFlow(np.zeros(self.wm.latent_dim)))
        
        if len(states) != len(actions) + 1:
            # Align: states is one longer than actions
            pass
        
        episode = FlowEpisode(
            states=[s.copy() for s in states[:len(actions)]],
            beliefs=[b.copy() for b in beliefs[:len(actions)]],
            actions=[a.copy() for a in actions],
            flow_embeddings=[
                self.wm.compute_flow_embedding(f) for f in step_flows
            ],
            rewards=rewards,
            flow_ids=[f.flow_id for f in step_flows],
            flow_types=[f.flow_type.value for f in step_flows]
        )
        
        self.record_episode(episode)
    
    def train_step(self) -> Dict:
        """
        One training step on flow-conditioned trajectories.
        
        1. Sample batch from buffer (with flow embeddings)
        2. Compute sequence loss (flow-conditioned)
        3. Update world model weights
        4. Update inverse dynamics
        """
        if len(self.buffer.episodes) < 2:
            return {'loss': float('inf'), 'status': 'insufficient_data'}
        
        batch = self.buffer.sample_batch(self.batch_size, self.seq_len)
        
        if not batch:
            return {'loss': float('inf'), 'status': 'empty_batch'}
        
        # Compute losses
        seq_loss = compute_flow_sequence_loss(self.wm, batch, self.k_steps)
        rew_loss = compute_flow_reward_loss(self.wm, batch)
        
        total_loss = seq_loss + 0.5 * rew_loss
        
        # Gradient update (simple SGD on all params)
        # Approximate gradients via finite differences on sample
        self._apply_gradient_update(total_loss, batch)
        
        self.training_step += 1
        self.loss_history.append(float(total_loss))
        
        return {
            'loss': float(total_loss),
            'seq_loss': float(seq_loss),
            'rew_loss': float(rew_loss),
            'n_batch': len(batch),
            'step': self.training_step
        }
    
    def _apply_gradient_update(self, loss: float, batch: List[Dict]):
        """
        Apply gradient update using Evolution Strategies (ES) gradient.
        
        ES estimates ∇_θ E[f(θ)] ≈ (1/N) * Σ (f(θ + σ*ε_i) - f(θ)) / σ * ε_i
        
        This is O(N) forward passes per step (N=16) instead of
        O(num_params) which would be thousands.
        """
        n_samples = 16
        sigma = 0.01
        lr = self.lr
        
        # Collect all parameters as a list of views
        param_list = [
            self.wm.W_t1, self.wm.b_t1,
            self.wm.W_t2, self.wm.b_t2,
            self.wm.W_t_logvar, self.wm.b_t_logvar,
            self.wm.W_zh, self.wm.W_zx, self.wm.b_z,
            self.wm.W_rh, self.wm.W_rx, self.wm.b_r,
            self.wm.W_hh, self.wm.W_hx, self.wm.b_h,
            self.wm.W_mu, self.wm.b_mu,
            self.wm.W_logvar, self.wm.b_logvar,
            self.wm.W_r1, self.wm.b_r1,
            self.wm.W_r2, self.wm.b_r2,
        ]
        
        # Store original parameters
        orig_params = [p.copy() for p in param_list]
        
        # ES gradient estimation
        grad_accum = [np.zeros_like(p) for p in param_list]
        
        for k in range(n_samples):
            # Generate random perturbations
            noises = [np.random.randn(*p.shape) * sigma for p in param_list]
            
            # Positive perturbation: θ + σ*ε
            for p, n in zip(param_list, noises):
                p[:] = p + n
            loss_pos = self._eval_loss(batch)
            
            # Negative perturbation: θ - σ*ε  
            for p, n in zip(param_list, noises):
                p[:] = p - 2 * n
            loss_neg = self._eval_loss(batch)
            
            # Gradient estimate: (f(θ+σ*ε) - f(θ-σ*ε)) / (2*σ) * ε
            delta = (loss_pos - loss_neg) / (2.0 * sigma)
            for g, n in zip(grad_accum, noises):
                g[:] = g + delta * n
            
            # Restore original parameters
            for p, orig in zip(param_list, orig_params):
                p[:] = orig
        
        # Average and apply update
        for p, g in zip(param_list, grad_accum):
            p[:] = p - lr * g / n_samples
    
    def _eval_loss(self, batch: List[Dict]) -> float:
        """Evaluate loss on batch (used for gradient estimation)."""
        seq_loss = compute_flow_sequence_loss(self.wm, batch, self.k_steps)
        rew_loss = compute_flow_reward_loss(self.wm, batch)
        return float(seq_loss + 0.5 * rew_loss)
    
    def validate(self) -> Dict:
        """Validate on held-out flow episodes."""
        if not self.val_episodes:
            return {'val_loss': float('inf')}
        
        val_batch = []
        for ep in self.val_episodes[:5]:
            if ep.length >= self.k_steps + 2:
                val_batch.append({
                    'x_seq': ep.states[:self.seq_len],
                    'a_seq': ep.actions[:self.seq_len],
                    'r_seq': ep.rewards[:self.seq_len],
                    'flow_embeds': ep.flow_embeddings[:self.seq_len],
                    'flow_ids': ep.flow_ids[:self.seq_len]
                })
        
        if not val_batch:
            return {'val_loss': float('inf')}
        
        loss = compute_flow_sequence_loss(self.wm, val_batch, self.k_steps)
        self.val_history.append(float(loss))
        
        return {
            'val_loss': float(loss),
            'n_val_episodes': len(val_batch),
            'n_total_episodes': len(self.val_episodes)
        }
    
    def get_training_report(self) -> Dict:
        """Report on training progress."""
        report = {
            'training_steps': self.training_step,
            'buffer_episodes': len(self.buffer.episodes),
            'buffer_transitions': self.buffer.total_transitions,
            'val_episodes': len(self.val_episodes),
        }
        
        if self.loss_history:
            recent = self.loss_history[-min(20, len(self.loss_history)):]
            report['recent_loss'] = float(np.mean(recent))
            report['initial_loss'] = float(self.loss_history[0])
            report['loss_improvement'] = (
                (self.loss_history[0] - recent[-1]) / max(1e-8, self.loss_history[0])
                if len(self.loss_history) > 1 else 0.0
            )
        
        if self.val_history:
            report['val_loss'] = float(self.val_history[-1])
        
        if self.buffer.episodes:
            report['flow_distribution'] = self.buffer.get_flow_distribution()
        
        return report


# ============================================================================
# 5. FULL CLOSED-LOOP EXECUTION
# ============================================================================

class ClosedLoopEngine:
    """
    Full closed-loop: execution ↔ training ↔ improvement.
    
    Integrates:
      Phase 35: DynamicalSkillEngine (flows)
      Phase 36: BehavioralPhysicsLearner (training)
    
    Loop per cycle:
      1. Execute goal with flows (Phase 35)
      2. Record trajectories (Phase 36 buffer)
      3. Train world model on flow data
      4. Train inverse dynamics
      5. Reorganize manifold
      6. Repeat with improved model
    """
    
    def __init__(
        self,
        world_model: FlowConditionedWorldModel,
        goal: GoalAttractor,
        manifold: Optional[FlowManifold] = None,
        n_initial_flows: int = 10,
        flow_dim: int = 8,
        learning_rate: float = 0.01,
        k_steps: int = 5,
        train_every_n_steps: int = 10
    ):
        self.wm = world_model
        self.goal = goal
        self.flow_dim = flow_dim
        
        # Inverse dynamics (Phase 34)
        self.inv_dyn = InverseDynamicsModel(
            latent_dim=world_model.latent_dim,
            action_dim=world_model.action_dim,
            learning_rate=0.01
        )
        
        # Manifold (Phase 35)
        self.manifold = manifold or FlowManifold(flow_dim=flow_dim)
        
        # Learner (this phase)
        self.learner = BehavioralPhysicsLearner(
            world_model=world_model,
            inv_dyn=self.inv_dyn,
            manifold=self.manifold,
            goal=goal,
            learning_rate=learning_rate,
            k_steps=k_steps
        )
        
        # Execution engine (Phase 35)
        self.engine = DynamicalSkillEngine(
            world_model=world_model,
            goal=goal,
            flow_manifold=self.manifold,
            inv_dyn=self.inv_dyn,
            n_initial_flows=0,
            flow_dim=flow_dim
        )
        
        # Seed flows
        if not self.manifold.flows:
            self._seed_flows(n_initial_flows)
        
        self.train_every_n = train_every_n_steps
        self.total_steps = 0
        self.cycle_log: List[Dict] = []
    
    def _seed_flows(self, n: int):
        """Seed initial flows in manifold."""
        for i in range(n):
            if random.random() < 0.6:
                target = np.random.randn(self.wm.latent_dim) * random.uniform(-1, 1) * 0.5
                flow = PointFlow(target, gain=random.uniform(0.2, 0.8))
            else:
                center = np.random.randn(self.wm.latent_dim) * 0.3
                flow = LimitCycleFlow(center, radius=random.uniform(0.5, 2.0),
                                      omega=random.uniform(0.2, 1.0))
            self.manifold.add_flow(flow, f'flow_{i}')
    
    def run_cycle(self, z_start: np.ndarray, n_steps: int = 20) -> Dict:
        """
        One closed-loop cycle.
        
        1. Execute with current flows (Phase 35)
        2. Record trajectories (Phase 36 buffer) with proper beliefs
        3. Train world model on flow data
        4. Report metrics
        """
        # Execute
        result = self.engine.execute_goal(z_start, max_steps=n_steps)
        
        # Reconstruct trajectory with beliefs from execution
        log = result.get('execution_log', [])
        states = [z_start.copy()]
        beliefs = [np.zeros(self.wm.belief_dim)]
        for entry in log:
            h = self.wm.gru_step(beliefs[-1], entry['z_before'])
            beliefs.append(h.copy())
            if 'z_after' in entry:
                states.append(entry['z_after'].copy())
            else:
                states.append(entry['z_before'].copy())
        
        if log:
            self.learner.record_from_engine(
                log,
                list(self.manifold.flows.values()),
                states,
                beliefs
            )
        
        # Train periodically
        train_result = {}
        if self.total_steps % self.train_every_n == 0:
            # Train for multiple steps
            train_losses = []
            for _ in range(5):
                tr = self.learner.train_step()
                if tr['loss'] != float('inf'):
                    train_losses.append(tr['loss'])
            
            if train_losses:
                train_result = {
                    'train_loss': float(np.mean(train_losses)),
                    'loss_trend': (train_losses[0] - train_losses[-1]) / max(1e-8, train_losses[0])
                }
            
            # Validate
            val = self.learner.validate()
            train_result['val_loss'] = val.get('val_loss', float('inf'))
        
        # Inverse dynamics training
        inv_loss = 0.0
        if len(self.inv_dyn.training_data) > 10:
            inv_loss = self.inv_dyn.train_from_buffer(
                self.inv_dyn.training_data[-100:]
            )
        
        self.total_steps += n_steps
        
        cycle_result = {
            'cycle': len(self.cycle_log),
            'goal_reached': result['goal_reached'],
            'goal_prob': result['final_goal_prob'],
            'n_flows': result['n_flows'],
            'stability': result['stability'],
            'training': train_result,
            'inv_dyn_loss': float(inv_loss),
            'buffer_stats': self.learner.buffer.get_stats() if hasattr(self.learner.buffer, 'get_stats') else {}
        }
        
        self.cycle_log.append(cycle_result)
        return cycle_result
    
    def run_multi_cycle(self, z_start: np.ndarray,
                        n_cycles: int = 5,
                        steps_per_cycle: int = 20,
                        carry_state: bool = True) -> Dict:
        """Run multiple closed-loop cycles with state carrying."""
        z = z_start.copy()
        
        for cycle in range(n_cycles):
            result = self.run_cycle(z, n_steps=steps_per_cycle)
            
            # Carry final state forward to next cycle
            if carry_state and self.cycle_log:
                last_z = self.engine.execution_log[-1]['z_after'] if self.engine.execution_log else None
                if last_z is not None:
                    z = last_z.copy()
        
        # Final report
        training_report = self.learner.get_training_report()
        
        goals_reached = sum(1 for c in self.cycle_log if c['goal_reached'])
        
        return {
            'n_cycles': n_cycles,
            'total_steps': self.total_steps,
            'goals_reached': goals_reached,
            'goal_rate': goals_reached / max(1, n_cycles),
            'training': training_report,
            'cycle_log': self.cycle_log[-5:]
        }


# ============================================================================
# 6. TESTS
# ============================================================================

def test_flow_conditioned_world_model():
    """Test flow-conditioned world model."""
    print("\n" + "=" * 60)
    print("FLOW-CONDITIONED WORLD MODEL TEST")
    print("=" * 60)
    
    wm = FlowConditionedWorldModel(
        event_dim=32, latent_dim=16, belief_dim=64,
        action_dim=16, flow_embed_dim=8
    )
    
    # Create flows
    pf = PointFlow(np.ones(16) * 0.5, gain=0.5)
    lc = LimitCycleFlow(np.zeros(16), radius=1.0, omega=0.5)
    
    # Compute embeddings
    emb_pf = wm.compute_flow_embedding(pf)
    emb_lc = wm.compute_flow_embedding(lc)
    
    print(f"\n  PointFlow embedding: norm={np.linalg.norm(emb_pf):.4f}")
    print(f"  LimitCycle embedding: norm={np.linalg.norm(emb_lc):.4f}")
    print(f"  Embedding similarity: {np.dot(emb_pf, emb_lc) / (np.linalg.norm(emb_pf) * np.linalg.norm(emb_lc) + 1e-8):.4f}")
    
    # Test flow-conditioned transition
    z = np.random.randn(16) * 0.5
    h = np.random.randn(64) * 0.1
    a = np.random.randn(16) * 0.3
    
    mu_pf, lv_pf = wm.predict_transition_flow(z, h, a, emb_pf)
    mu_lc, lv_lc = wm.predict_transition_flow(z, h, a, emb_lc)
    
    print(f"\n  PF transition norm: {np.linalg.norm(mu_pf):.4f}")
    print(f"  LC transition norm: {np.linalg.norm(mu_lc):.4f}")
    print(f"  Transition diff: {np.linalg.norm(mu_pf - mu_lc):.4f}")
    
    print("\n  ✓ Flow-conditioned world model operational")


def test_flow_trajectory_buffer():
    """Test flow trajectory buffer."""
    print("\n" + "=" * 60)
    print("FLOW TRAJECTORY BUFFER TEST")
    print("=" * 60)
    
    buffer = FlowTrajectoryBuffer(max_episodes=10)
    
    # Create fake episodes
    for i in range(5):
        ep = FlowEpisode(
            states=[np.random.randn(16) * 0.5 for _ in range(10)],
            beliefs=[np.random.randn(64) * 0.1 for _ in range(10)],
            actions=[np.random.randn(16) * 0.3 for _ in range(10)],
            flow_embeddings=[np.random.randn(8) for _ in range(10)],
            rewards=[random.random() for _ in range(10)],
            flow_ids=[f'flow_{i % 3}' for _ in range(10)],
            flow_types=['point_attractor' if i % 2 == 0 else 'limit_cycle' for _ in range(10)]
        )
        buffer.add_episode(ep)
    
    stats = buffer.get_stats()
    print(f"\n  Episodes: {stats['n_episodes']}")
    print(f"  Transitions: {stats['n_transitions']}")
    print(f"  Avg length: {stats['avg_length']:.1f}")
    
    # Test sampling
    batch = buffer.sample_batch(batch_size=4, seq_len=5)
    print(f"  Batch size: {len(batch)}")
    
    if batch:
        print(f"  Sample keys: {list(batch[0].keys())}")
        print(f"  x_seq len: {len(batch[0]['x_seq'])}")
        print(f"  flow_embeds len: {len(batch[0]['flow_embeds'])}")
    
    # Flow distribution
    dist = buffer.get_flow_distribution()
    print(f"  Flow distribution: {dist}")
    
    print("\n  ✓ Flow trajectory buffer operational")


def test_flow_sequence_loss():
    """Test flow-conditioned sequence loss."""
    print("\n" + "=" * 60)
    print("FLOW SEQUENCE LOSS TEST")
    print("=" * 60)
    
    wm = FlowConditionedWorldModel(
        event_dim=32, latent_dim=16, belief_dim=64,
        action_dim=16, flow_embed_dim=8
    )
    
    # Create synthetic batch with flow embeddings
    batch = []
    for _ in range(4):
        seq_len = 12
        flow_embeds = []
        for t in range(seq_len):
            if random.random() < 0.5:
                embed = wm.compute_flow_embedding(
                    PointFlow(np.random.randn(16) * 0.5)
                )
            else:
                embed = wm.compute_flow_embedding(
                    LimitCycleFlow(np.random.randn(16) * 0.3, radius=1.0, omega=0.5)
                )
            flow_embeds.append(embed)
        
        batch.append({
            'x_seq': [np.random.randn(32) * 0.5 for _ in range(seq_len)],
            'a_seq': [np.random.randn(16) * 0.3 for _ in range(seq_len)],
            'r_seq': [random.random() for _ in range(seq_len)],
            'flow_embeds': flow_embeds,
            'flow_ids': [f'flow_{t % 3}' for t in range(seq_len)]
        })
    
    loss = compute_flow_sequence_loss(wm, batch, k_steps=3)
    rew_loss = compute_flow_reward_loss(wm, batch)
    
    print(f"\n  Sequence loss: {loss:.4f}")
    print(f"  Reward loss: {rew_loss:.4f}")
    
    # Loss should be finite
    print(f"  Loss finite: {np.isfinite(loss)}")
    
    print("\n  ✓ Flow sequence loss operational")


def test_closed_loop_execution():
    """Test full closed-loop execution."""
    print("\n" + "=" * 60)
    print("CLOSED-LOOP EXECUTION TEST")
    print("=" * 60)
    
    wm = FlowConditionedWorldModel(
        event_dim=32, latent_dim=16, belief_dim=64,
        action_dim=16, flow_embed_dim=8
    )
    
    goal = GoalAttractor(
        goal_id='closed_goal',
        attractor_state=np.ones(16) * 1.5,
        basin_radius=2.0,
        priority=0.9,
        decay_rate=0.01,
        success_criteria={'type': 'achievable'}
    )
    
    engine = ClosedLoopEngine(
        world_model=wm,
        goal=goal,
        n_initial_flows=8,
        flow_dim=4,
        train_every_n_steps=10
    )
    
    # Run a few cycles
    result = engine.run_multi_cycle(
        np.zeros(16),
        n_cycles=3,
        steps_per_cycle=10
    )
    
    print(f"\n  Total cycles: {result['n_cycles']}")
    print(f"  Total steps: {result['total_steps']}")
    print(f"  Goals reached: {result['goals_reached']}")
    
    tr = result['training']
    print(f"\n  Training:")
    print(f"    Steps: {tr['training_steps']}")
    print(f"    Buffer: {tr['buffer_episodes']} episodes, {tr['buffer_transitions']} transitions")
    
    if 'loss_improvement' in tr:
        print(f"    Loss improvement: {tr.get('loss_improvement', 0) * 100:.1f}%")
    
    if tr.get('val_loss', float('inf')) != float('inf'):
        print(f"    Val loss: {tr['val_loss']:.4f}")
    
    print("\n  ✓ Closed-loop execution operational")


if __name__ == "__main__":
    test_flow_conditioned_world_model()
    test_flow_trajectory_buffer()
    test_flow_sequence_loss()
    test_closed_loop_execution()
    
    print("\n" + "=" * 60)
    print("PHASE 36: EXECUTION-CONSISTENT BEHAVIORAL PHYSICS")
    print("=" * 60)
    
    print("""
CLOSES THE LOOP:
  Phase 35 flows → trajectory → world model update →
  inverse dynamics update → manifold reorganization → better flows

WHAT CHANGED FROM PHASE 30 WORLD MODEL:
  Phase 30: P(z_{t+1} | z_t, h_t, a_t)  ← action-only
  Phase 36: P(z_{t+1} | z_t, h_t, a_t, π)  ← flow-conditioned

KEY COMPONENTS:
  1. FlowConditionedWorldModel — extended transition with flow embedding
  2. FlowTrajectoryBuffer — episodes with flow metadata
  3. Flow-conditioned sequence loss — multi-step with flow context
  4. ClosedLoopEngine — execute → record → train → improve

METRICS THAT NOW MATTER:
  - Prediction error on flow-generated trajectories (BEFORE is more important than AFTER)
  - Inverse dynamics error on real transitions
  - Goal probability trend over training cycles
  
ARCHITECTURAL PROGRESSION:
  Phase 33: point attractor        (dead consistency)
  Phase 34: inverse dynamics       (correct stabilization)
  Phase 35: dynamical flows        (state-dependent policy)
  Phase 36: behavioral physics     (substrate learns from flows)

NEXT (Phase 37):
  Controllability topology — organize manifold by reachability,
  not by action similarity or trajectory similarity.
""")
