"""
Phase 35 — Dynamical Skill Flows

KEY SHIFT:
  BEFORE: skill = static action vector (point attractor)
          a = attractor_point  ← frozen, state-independent
  
  AFTER:  skill = local dynamical system (vector field policy)
          a_t = π_skill(z_t, h_t)  ← state-dependent, closed-loop
  
  A skill is no longer an action.
  A skill is a flow regime in state space.

FLOW TYPES:
  - PointFlow:      a = K * (z_target - z)         → converge to point
  - LimitCycleFlow:  a = ω*R*z + K*(r - |z-c|)*(z-c) → stable oscillation
  - LinearFlow:      a = A @ z + b                  → general linear dynamics
  - ComposedFlow:    a = Σ w_i * π_i(z, h)          → superposition of flows

ARCHITECTURAL IMPACT:
  Execution is no longer:  coord → action → transition
  Execution becomes:       coord → local flow → trajectory shaping
  
  This enables:
    - Temporal coordination (oscillation, phase)
    - Recovery dynamics (flow always has a direction)
    - Closed-loop correction (action depends on state)
    - Skill composition (superposition of flows)
    
  And critically:
    World model training becomes MEANINGFUL
    because trajectories are generated by persistent control dynamics,
    not by random actions or static attractors.
"""

import numpy as np
import random
from typing import List, Dict, Tuple, Optional, Any, Callable
from dataclasses import dataclass, field
from enum import Enum

from phase30_training_loop import MinimalWorldModel
from phase31_hierarchical_execution import GoalAttractor
from phase32_skill_dynamics_coupling import (
    SkillDynamicsAdapter, ProbabilisticGoalEvaluator
)
from phase34_inverse_control_stabilization import (
    InverseDynamicsModel, InverseAttractorStabilizer
)


# ============================================================================
# 1. FLOW TYPES (Local Dynamical Systems)
# ============================================================================

class FlowType(Enum):
    POINT = "point_attractor"
    LIMIT_CYCLE = "limit_cycle"
    LINEAR = "linear_flow"
    COMPOSED = "composed_flow"


class SkillFlow:
    """
    Base class for dynamical skill flows.
    
    A flow is a policy: π(z, h) → a
    It defines a local dynamical regime in state space.
    
    Unlike a point attractor (static action), a flow produces
    different actions depending on current state — this enables
    closed-loop control, oscillation, and recovery.
    """
    
    def __init__(self, flow_type: FlowType):
        self.flow_type = flow_type
        self.flow_id: str = ""
        
        # Stability metrics
        self.stability: float = 0.5
        self.goal_alignment: float = 0.0
        self.age: int = 0
        
        # Execution history
        self.execution_trace: List[Dict] = []
        self.max_history: int = 50
    
    def compute_action(self, z: np.ndarray, h: np.ndarray) -> np.ndarray:
        """
        π(z, h) → a
        
        The core of the flow — state-dependent action generation.
        """
        raise NotImplementedError
    
    def get_parameters(self) -> np.ndarray:
        """Get flow parameters as flat vector (for CEM)."""
        raise NotImplementedError
    
    def set_parameters(self, params: np.ndarray):
        """Set flow parameters from flat vector."""
        raise NotImplementedError
    
    def parameter_dim(self) -> int:
        """Dimension of parameter space for CEM."""
        raise NotImplementedError
    
    def record_transition(self, z_before: np.ndarray, z_after: np.ndarray,
                          a: np.ndarray, h: np.ndarray):
        """Record execution step."""
        self.execution_trace.append({
            'z_before': z_before.copy(),
            'z_after': z_after.copy(),
            'action': a.copy(),
            'h': h.copy()
        })
        if len(self.execution_trace) > self.max_history:
            self.execution_trace.pop(0)
        self.age += 1
    
    def compute_lyapunov_estimate(self) -> float:
        """
        Estimate Lyapunov exponent from execution trace.
        
        λ < 0 → stable (convergent)
        λ ≈ 0 → limit cycle (neutrally stable)
        λ > 0 → chaotic (divergent)
        
        Returns: normalized stability [0, 1] where 1 = most stable
        """
        if len(self.execution_trace) < 5:
            return self.stability
        
        deltas = np.array([
            t['z_after'] - t['z_before']
            for t in self.execution_trace[-20:]
        ])
        
        if len(deltas) < 2:
            return self.stability
        
        # Estimate expansion/contraction rate
        diffs = deltas[1:] - deltas[:-1]
        
        if np.linalg.norm(deltas[-1]) < 1e-8:
            contraction = 0.0
        else:
            contraction = np.linalg.norm(deltas[-1]) / (np.linalg.norm(deltas[0]) + 1e-8)
        
        # Normalize: 0 = divergent, 1 = convergent
        stability = 1.0 / (1.0 + max(0, contraction))
        
        return float(np.clip(stability, 0.0, 1.0))


class PointFlow(SkillFlow):
    """
    Linear point attractor: a = K * (z_target - z)
    
    Pulls the system toward a target state.
    Most common skill regime — "reach for goal."
    
    Parameters: z_target (latent_dim), K (scalar gain)
    """
    
    def __init__(self, z_target: np.ndarray, gain: float = 0.5, latent_dim: int = 16):
        super().__init__(FlowType.POINT)
        self.latent_dim = latent_dim
        self.z_target = np.asarray(z_target).flatten()[:latent_dim].copy()
        self.gain = gain
    
    def compute_action(self, z: np.ndarray, h: np.ndarray) -> np.ndarray:
        """a = K * (z_target - z)"""
        z = np.asarray(z).flatten()[:self.latent_dim]
        action = self.gain * (self.z_target - z)
        return action
    
    def get_parameters(self) -> np.ndarray:
        """[z_target (latent_dim), gain (1)]"""
        return np.concatenate([self.z_target, [self.gain]])
    
    def set_parameters(self, params: np.ndarray):
        self.z_target = params[:self.latent_dim].copy()
        self.gain = float(params[self.latent_dim])
    
    def parameter_dim(self) -> int:
        return self.latent_dim + 1
    
    def __repr__(self) -> str:
        return (f"PointFlow(target_norm={np.linalg.norm(self.z_target):.2f}, "
                f"gain={self.gain:.2f})")


class LimitCycleFlow(SkillFlow):
    """
    Stable limit cycle: oscillation around a center.
    
    Tangential component: ω * R_90 * (z - center)  → rotation
    Radial component:    K * (r - |z-c|) * (z-c)   → radial stability
    
    This represents oscillatory skills like:
      walking, swimming, periodic sampling, rhythmic behaviors
    
    Parameters: center (latent_dim), radius (1), omega (1), K_radial (1)
    """
    
    def __init__(self, center: np.ndarray, radius: float = 1.0,
                 omega: float = 0.5, K_radial: float = 0.3,
                 latent_dim: int = 16):
        super().__init__(FlowType.LIMIT_CYCLE)
        self.latent_dim = latent_dim
        self.center = np.asarray(center).flatten()[:latent_dim].copy()
        self.radius = radius
        self.omega = omega
        self.K_radial = K_radial
        
        # 90-degree rotation matrix (tangential direction)
        self.R = np.zeros((latent_dim, latent_dim))
        for i in range(latent_dim - 1):
            self.R[i, i + 1] = 1.0
            self.R[i + 1, i] = -1.0
    
    def compute_action(self, z: np.ndarray, h: np.ndarray) -> np.ndarray:
        """a = ω * R * (z - c) + K * (r - |z-c|) * (z-c) / |z-c|"""
        z = np.asarray(z).flatten()[:self.latent_dim]
        diff = z - self.center
        dist = np.linalg.norm(diff)
        
        if dist < 1e-8:
            diff_unit = np.zeros(self.latent_dim)
        else:
            diff_unit = diff / dist
        
        # Tangential (rotational)
        tangential = self.omega * self.R @ diff
        
        # Radial (stabilization toward radius)
        radial = self.K_radial * (self.radius - dist) * diff_unit
        
        return tangential + radial
    
    def get_parameters(self) -> np.ndarray:
        """[center (latent_dim), radius (1), omega (1), K_radial (1)]"""
        return np.concatenate([self.center, [self.radius, self.omega, self.K_radial]])
    
    def set_parameters(self, params: np.ndarray):
        self.center = params[:self.latent_dim].copy()
        self.radius = float(params[self.latent_dim])
        self.omega = float(params[self.latent_dim + 1])
        self.K_radial = float(params[self.latent_dim + 2])
    
    def parameter_dim(self) -> int:
        return self.latent_dim + 3
    
    def __repr__(self) -> str:
        return (f"LimitCycle(center_norm={np.linalg.norm(self.center):.2f}, "
                f"r={self.radius:.2f}, ω={self.omega:.2f})")


class LinearFlow(SkillFlow):
    """
    General linear dynamics: a = A @ z + b
    
    Can represent:
      - Exponential decay (negative eigenvalues)
      - Oscillation (complex eigenvalues)  
      - Growth (positive eigenvalues)
      - Fixed point shifts (bias term)
    
    Parameters: A (latent_dim × latent_dim), b (latent_dim)
    """
    
    def __init__(self, latent_dim: int = 16):
        super().__init__(FlowType.LINEAR)
        self.latent_dim = latent_dim
        
        # Initialize as stable (negative diagonal)
        scale = 0.1
        self.A = -np.eye(latent_dim) * scale + np.random.randn(latent_dim, latent_dim) * scale * 0.3
        self.b = np.zeros(latent_dim)
    
    def compute_action(self, z: np.ndarray, h: np.ndarray) -> np.ndarray:
        """a = A @ z + b"""
        z = np.asarray(z).flatten()[:self.latent_dim]
        return self.A @ z + self.b
    
    def get_parameters(self) -> np.ndarray:
        """[A.flatten (latent_dim²), b (latent_dim)]"""
        return np.concatenate([self.A.flatten(), self.b])
    
    def set_parameters(self, params: np.ndarray):
        A_size = self.latent_dim * self.latent_dim
        self.A = params[:A_size].reshape(self.latent_dim, self.latent_dim)
        self.b = params[A_size:].copy()
    
    def parameter_dim(self) -> int:
        return self.latent_dim * self.latent_dim + self.latent_dim


class ComposedFlow(SkillFlow):
    """
    Superposition of multiple flows: a = Σ w_i * π_i(z, h)
    
    This is how skills compose — by blending their vector fields.
    Composition enables complex behaviors from simple primitives.
    """
    
    def __init__(self, flows: List[SkillFlow], weights: Optional[List[float]] = None):
        super().__init__(FlowType.COMPOSED)
        self.flows = flows
        self.weights = weights or [1.0 / len(flows)] * len(flows)
    
    def compute_action(self, z: np.ndarray, h: np.ndarray) -> np.ndarray:
        """a = Σ w_i * π_i(z, h)"""
        actions = [w * f.compute_action(z, h) for w, f in zip(self.weights, self.flows)]
        return sum(actions)
    
    def get_parameters(self) -> np.ndarray:
        return np.array(self.weights)
    
    def set_parameters(self, params: np.ndarray):
        self.weights = params.tolist()
    
    def parameter_dim(self) -> int:
        return len(self.flows)


# ============================================================================
# 2. FLOW EXECUTION (Rollout through World Model)
# ============================================================================

def rollout_flow(
    flow: SkillFlow,
    z_start: np.ndarray,
    h_start: np.ndarray,
    world_model: MinimalWorldModel,
    n_steps: int = 10,
    noise_scale: float = 0.0
) -> Dict:
    """
    Execute flow through world model for n_steps.
    
    Each step:
      1. a_t = flow.compute_action(z_t, h_t)   ← flow policy
      2. z_{t+1} = world_model(z_t, h_t, a_t)  ← world dynamics
      3. record transition
    
    Returns: full trajectory + metrics
    """
    z = z_start.copy()
    h = h_start.copy()
    
    states = [z.copy()]
    beliefs = [h.copy()]
    actions = []
    goal_probs = []
    uncertainties = []
    
    for step in range(n_steps):
        a = flow.compute_action(z, h)
        
        mu, logvar = world_model.predict_transition(z, h, a)
        
        if noise_scale > 0:
            std = np.exp(0.5 * logvar)
            z_next = mu + std * np.random.randn(*mu.shape) * noise_scale
        else:
            z_next = mu
        
        h = world_model.gru_step(h, mu)
        
        flow.record_transition(z, z_next, a, h)
        
        states.append(z_next.copy())
        beliefs.append(h.copy())
        actions.append(a.copy())
        uncertainties.append(float(np.mean(np.exp(logvar))))
        
        z = z_next.copy()
    
    return {
        'states': np.array(states),
        'beliefs': beliefs,
        'actions': np.array(actions),
        'uncertainties': uncertainties,
        'final_state': z.copy(),
        'final_belief': h.copy(),
        'n_steps': n_steps
    }


def evaluate_flow_goal(
    flow: SkillFlow,
    z_start: np.ndarray,
    h_start: np.ndarray,
    goal: GoalAttractor,
    world_model: MinimalWorldModel,
    n_steps: int = 10
) -> float:
    """
    Evaluate flow's expected goal satisfaction.
    
    Score = P(goal | trajectory) - λ * uncertainty
    """
    result = rollout_flow(flow, z_start, h_start, world_model, n_steps)
    
    z_final = result['final_state']
    dist = np.linalg.norm(z_final - goal.attractor_state[:len(z_final)])
    
    goal_prob = np.exp(-dist)
    avg_uncertainty = np.mean(result['uncertainties']) if result['uncertainties'] else 0.0
    
    return float(goal_prob - 0.1 * avg_uncertainty)


# ============================================================================
# 3. FLOW MANIFOLD (Continuous Space of Dynamical Regimes)
# ============================================================================

class FlowManifold:
    """
    Manifold over dynamical skill flows.
    
    Unlike Phase 33's SkillManifold (which interpolated action vectors),
    this manifold interpolates FLOW BEHAVIORS.
    
    Similarity on this manifold = similar DYNAMICS, not similar actions.
    
    Organization principles:
      - Nearby flows produce similar trajectories from same start state
      - The manifold is a "behavior space" not an "action space"
    """
    
    def __init__(self, flow_dim: int = 8):
        self.flow_dim = flow_dim
        self.flows: Dict[str, SkillFlow] = {}
        self.flow_coords: Dict[str, np.ndarray] = {}
        
        # Learned embedding: flow parameters → manifold coordinate
        self.embedding_projection: Optional[np.ndarray] = None
    
    def add_flow(self, flow: SkillFlow, flow_id: str,
                 coord: Optional[np.ndarray] = None):
        """Add flow to manifold."""
        flow.flow_id = flow_id
        self.flows[flow_id] = flow
        
        if coord is None:
            coord = np.random.randn(self.flow_dim) * 0.5
        
        self.flow_coords[flow_id] = coord
    
    def interpolate_at(self, coord: np.ndarray,
                       world_model: Optional[MinimalWorldModel] = None,
                       z_test: Optional[np.ndarray] = None) -> ComposedFlow:
        """
        Interpolate flows at manifold coordinate.
        
        Returns a ComposedFlow that blends nearby flows weighted by:
          - inverse distance on manifold
          - flow stability
        
        This is the key operation: coordinate → blended dynamics
        """
        if not self.flows:
            return PointFlow(np.zeros(16))
        
        # Find distances
        distances = []
        for fid, c in self.flow_coords.items():
            dist = np.linalg.norm(coord - c)
            flow = self.flows[fid]
            distances.append((dist, fid, flow))
        
        distances.sort(key=lambda x: x[0])
        
        # Blend k-nearest flows
        k = min(4, len(distances))
        nearest = distances[:k]
        
        total_weight = 0.0
        weights = []
        blend_flows = []
        
        for dist, fid, flow in nearest:
            w = flow.stability / (dist + 0.1)
            weights.append(w)
            blend_flows.append(flow)
            total_weight += w
        
        if total_weight > 0:
            weights = [w / total_weight for w in weights]
        else:
            weights = [1.0 / k] * k
        
        return ComposedFlow(blend_flows, weights)
    
    def compute_similarity(self, flow_id_1: str, flow_id_2: str,
                           world_model: MinimalWorldModel,
                           z_test: np.ndarray,
                           n_steps: int = 10) -> float:
        """
        Compute behavioral similarity between two flows.
        
        Two flows are similar if they produce similar trajectories
        from the same starting state.
        
        This is the foundation for topological organization.
        """
        if flow_id_1 not in self.flows or flow_id_2 not in self.flows:
            return 0.0
        
        h = np.zeros(world_model.belief_dim)
        
        traj_1 = rollout_flow(self.flows[flow_id_1], z_test, h, world_model, n_steps)
        traj_2 = rollout_flow(self.flows[flow_id_2], z_test, h, world_model, n_steps)
        
        states_1 = traj_1['states']
        states_2 = traj_2['states']
        
        # Dynamic Time Warping-style similarity
        diffs = np.mean((states_1 - states_2) ** 2, axis=1)
        similarity = np.exp(-np.mean(diffs))
        
        return float(similarity)
    
    def organize_topology(self, world_model: MinimalWorldModel,
                          z_test: np.ndarray, n_steps: int = 10):
        """
        Reorganize manifold coordinates based on behavioral similarity.
        
        Flows with similar dynamics get moved closer together.
        This is the "topology learning" step.
        """
        if len(self.flows) < 2:
            return
        
        flow_ids = list(self.flows.keys())
        
        # Compute pairwise similarity
        n = len(flow_ids)
        sim_matrix = np.zeros((n, n))
        
        for i in range(n):
            for j in range(i + 1, n):
                sim = self.compute_similarity(
                    flow_ids[i], flow_ids[j], world_model, z_test, n_steps
                )
                sim_matrix[i, j] = sim
                sim_matrix[j, i] = sim
            sim_matrix[i, i] = 1.0
        
        # Update coordinates: similar flows → closer in manifold
        # Simple approach: MDS-style update
        for i in range(n):
            weighted_displacement = np.zeros(self.flow_dim)
            total_weight = 0.0
            
            for j in range(n):
                if i == j:
                    continue
                
                target_dist = 1.0 - sim_matrix[i, j]  # Similar → small distance
                current_dist = np.linalg.norm(
                    self.flow_coords[flow_ids[i]] - self.flow_coords[flow_ids[j]]
                )
                
                if current_dist > 1e-8:
                    direction = (self.flow_coords[flow_ids[j]] - self.flow_coords[flow_ids[i]]) / current_dist
                    displacement = direction * (current_dist - target_dist * 3.0)
                    w = sim_matrix[i, j] ** 2  # Similar flows pull harder
                    
                    weighted_displacement += w * displacement
                    total_weight += w
            
            if total_weight > 0:
                self.flow_coords[flow_ids[i]] += 0.05 * weighted_displacement / total_weight


# ============================================================================
# 4. FLOW-CONDITIONED CEM
# ============================================================================

class FlowCEM:
    """
    CEM planner over flow parameter space.
    
    NOT discrete skill indices.
    NOT action vectors.
    
    Samples FLOW PARAMETERS → evaluates trajectory via world model.
    
    The key insight: CEM now optimizes DYNAMICAL REGIMES,
    not individual actions or discrete skills.
    """
    
    def __init__(
        self,
        world_model: MinimalWorldModel,
        manifold: FlowManifold,
        evaluator: ProbabilisticGoalEvaluator,
        flow_dim: int = 8,
        n_candidates: int = 80,
        n_elites: int = 16,
        n_iterations: int = 5,
        stability_bonus: float = 0.2,
        entropy_coeff: float = 0.05,
        rollout_steps: int = 8
    ):
        self.wm = world_model
        self.manifold = manifold
        self.evaluator = evaluator
        self.flow_dim = flow_dim
        self.n_candidates = n_candidates
        self.n_elites = n_elites
        self.n_iterations = n_iterations
        self.stability_bonus = stability_bonus
        self.entropy_coeff = entropy_coeff
        self.rollout_steps = rollout_steps
        
        self.mean = np.zeros(flow_dim)
        self.std = np.ones(flow_dim)
    
    def plan_flow(
        self,
        z_start: np.ndarray,
        h_start: np.ndarray,
        goal: GoalAttractor
    ) -> Dict:
        """
        Plan flow by optimizing manifold coordinate.
        
        Returns: {coord, flow, score, trajectory}
        """
        if not self.manifold.flows:
            return {'coord': np.zeros(self.flow_dim), 'flow': None,
                    'score': -np.inf, 'trajectory': None}
        
        self.mean = np.zeros(self.flow_dim)
        self.std = np.ones(self.flow_dim)
        
        best_coord = None
        best_score = -np.inf
        best_trajectory = None
        
        for iteration in range(self.n_iterations):
            # Sample candidate manifold coordinates
            candidates = []
            for _ in range(self.n_candidates):
                coord = self.mean + self.std * np.random.randn(self.flow_dim)
                candidates.append(coord)
            
            # Evaluate each coordinate
            scores = []
            trajectories = []
            for coord in candidates:
                flow = self.manifold.interpolate_at(coord, self.wm, z_start)
                result = rollout_flow(flow, z_start, h_start, self.wm, self.rollout_steps)
                
                # Score = goal probability + stability bonus - uncertainty penalty
                z_final = result['final_state']
                dist = np.linalg.norm(z_final - goal.attractor_state[:len(z_final)])
                goal_prob = np.exp(-dist)
                
                # Stability of constituent flows
                avg_stability = np.mean([f.stability for f in flow.flows])
                
                # Uncertainty
                avg_uncertainty = np.mean(result['uncertainties']) if result['uncertainties'] else 0.0
                
                score = (goal_prob
                         + self.stability_bonus * avg_stability
                         - 0.1 * avg_uncertainty)
                
                scores.append(score)
                trajectories.append(result)
            
            # Select elites
            elite_indices = np.argsort(scores)[-self.n_elites:]
            elite_coords = [candidates[i] for i in elite_indices]
            
            # Update distribution
            if elite_coords:
                self.mean = np.mean(elite_coords, axis=0)
                self.std = np.std(elite_coords, axis=0) + 0.1
            
            # Track best
            max_idx = int(np.argmax(scores))
            if scores[max_idx] > best_score:
                best_score = scores[max_idx]
                best_coord = candidates[max_idx]
                best_trajectory = trajectories[max_idx]
        
        if best_coord is None:
            return {'coord': np.zeros(self.flow_dim), 'flow': None,
                    'score': -np.inf, 'trajectory': None}
        
        best_flow = self.manifold.interpolate_at(best_coord, self.wm, z_start)
        
        return {
            'coord': best_coord,
            'flow': best_flow,
            'score': float(best_score),
            'trajectory': best_trajectory
        }


# ============================================================================
# 5. DYNAMICAL SKILL ENGINE (Full Integration)
# ============================================================================

class DynamicalSkillEngine:
    """
    Complete execution engine with dynamical skill flows.
    
    Integrates:
      Phase 30: World model
      Phase 34: Inverse dynamics  
      Phase 35: Skill flows (this phase)
    
    Execution loop:
      CEM → manifold coordinate → blended flow → rollout → 
      evaluate → stabilize → update manifold topology
    """
    
    def __init__(
        self,
        world_model: MinimalWorldModel,
        goal: GoalAttractor,
        flow_manifold: Optional[FlowManifold] = None,
        inv_dyn: Optional[InverseDynamicsModel] = None,
        n_initial_flows: int = 8,
        flow_dim: int = 8
    ):
        self.wm = world_model
        self.goal = goal
        self.flow_dim = flow_dim
        
        # Flow manifold
        self.manifold = flow_manifold or FlowManifold(flow_dim=flow_dim)
        
        # Inverse dynamics (from Phase 34)
        self.inv_dyn = inv_dyn or InverseDynamicsModel(
            latent_dim=world_model.latent_dim,
            action_dim=world_model.action_dim
        )
        
        # Adapters
        self.adapter = SkillDynamicsAdapter(world_model)
        self.evaluator = ProbabilisticGoalEvaluator(world_model)
        
        # Seed initial flows
        if not self.manifold.flows:
            self._seed_flows(n_initial_flows)
        
        # CEM
        self.cem = FlowCEM(
            world_model=self.wm,
            manifold=self.manifold,
            evaluator=self.evaluator,
            flow_dim=flow_dim
        )
        
        # Execution state
        self.execution_log: List[Dict] = []
    
    def _seed_flows(self, n: int):
        """Seed initial flow regimes."""
        for i in range(n):
            flow_type = random.choice([FlowType.POINT, FlowType.LIMIT_CYCLE, FlowType.POINT])
            
            if flow_type == FlowType.POINT:
                target = np.random.randn(self.wm.latent_dim) * 0.5
                flow = PointFlow(target, gain=random.uniform(0.2, 0.8))
            elif flow_type == FlowType.LIMIT_CYCLE:
                center = np.random.randn(self.wm.latent_dim) * 0.3
                flow = LimitCycleFlow(center, radius=random.uniform(0.5, 2.0),
                                      omega=random.uniform(0.2, 1.0))
            else:
                flow = LinearFlow(latent_dim=self.wm.latent_dim)
            
            self.manifold.add_flow(flow, f'seed_{i}')
    
    def execute_step(self, z: np.ndarray, h: np.ndarray) -> Dict:
        """
        One execution step with flow dynamics.
        
        1. CEM plans flow coordinate
        2. Flow generates action
        3. World model transitions
        4. Train inverse dynamics
        5. Update manifold topology
        """
        # 1. Plan flow
        plan = self.cem.plan_flow(z, h, self.goal)
        
        if plan['flow'] is None:
            # Fallback: nearest flow
            if self.manifold.flows:
                flow = list(self.manifold.flows.values())[0]
            else:
                flow = PointFlow(np.zeros(self.wm.latent_dim))
        else:
            flow = plan['flow']
        
        # 2. Generate action from flow
        a = flow.compute_action(z, h)
        
        # 3. Apply through world model
        mu, logvar = self.wm.predict_transition(z, h, a)
        std = np.exp(0.5 * logvar)
        z_next = mu + std * np.random.randn(*mu.shape) * 0.1
        h_next = self.wm.gru_step(h, mu)
        
        # Record
        flow.record_transition(z, z_next, a, h)
        
        # 4. Train inverse dynamics
        self.inv_dyn.train_step(z, z_next, a)
        self.inv_dyn.add_transition(z, z_next, a)
        
        # 5. Evaluate
        goal_prob = self.evaluator.goal_satisfaction_probability(self.goal, mu, logvar)
        
        # Update flow stability
        flow.stability = flow.compute_lyapunov_estimate()
        
        step_result = {
            'z_before': z.copy(),
            'z_after': z_next.copy(),
            'action': a.copy(),
            'goal_prob': float(goal_prob),
            'flow_type': flow.flow_type.value,
            'flow_id': flow.flow_id,
            'stability': flow.stability,
            'n_flows': len(self.manifold.flows)
        }
        
        self.execution_log.append(step_result)
        return step_result
    
    def execute_goal(self, z_start: np.ndarray, max_steps: int = 50) -> Dict:
        """Execute full goal with flow dynamics."""
        z = z_start.copy()
        h = np.zeros(self.wm.belief_dim)
        h = self.wm.gru_step(h, z)
        
        all_states = [z.copy()]
        goal_reached = False
        
        for step in range(max_steps):
            result = self.execute_step(z, h)
            
            if result['goal_prob'] > 0.7:
                goal_reached = True
            
            z = result['z_after'].copy()
            h = self.wm.gru_step(h, result['z_after'])
            all_states.append(z.copy())
        
        # Organize manifold topology
        if len(self.manifold.flows) >= 2 and len(all_states) > 5:
            self.manifold.organize_topology(
                self.wm, all_states[len(all_states) // 2], n_steps=5
            )
        
        # Get stability report
        stabilities = [f.stability for f in self.manifold.flows.values()]
        flow_types = [f.flow_type.value for f in self.manifold.flows.values()]
        
        return {
            'goal_reached': goal_reached,
            'final_goal_prob': self.execution_log[-1]['goal_prob'] if self.execution_log else 0.0,
            'n_steps': len(self.execution_log),
            'n_flows': len(self.manifold.flows),
            'flow_types': {t: flow_types.count(t) for t in set(flow_types)},
            'stability': {
                'mean': float(np.mean(stabilities)) if stabilities else 0.0,
                'max': float(max(stabilities)) if stabilities else 0.0,
                'min': float(min(stabilities)) if stabilities else 0.0
            },
            'execution_log': self.execution_log[-10:],
            'trajectory_length': len(all_states)
        }


# ============================================================================
# 6. TESTS
# ============================================================================

def test_flow_types():
    """Test all flow types."""
    print("\n" + "=" * 60)
    print("FLOW TYPES TEST")
    print("=" * 60)
    
    wm = MinimalWorldModel(event_dim=32, latent_dim=16, belief_dim=64, action_dim=16)
    z = np.random.randn(16) * 0.5
    h = np.random.randn(64) * 0.1
    
    # Point flow
    pf = PointFlow(np.ones(16) * 0.5, gain=0.5)
    a = pf.compute_action(z, h)
    print(f"\n  PointFlow action norm: {np.linalg.norm(a):.4f}")
    
    mu, _ = wm.predict_transition(z, h, a)
    print(f"  PointFlow transition norm: {np.linalg.norm(mu):.4f}")
    
    # Limit cycle flow
    lc = LimitCycleFlow(np.zeros(16), radius=1.0, omega=0.5)
    a_lc = lc.compute_action(z, h)
    print(f"\n  LimitCycle action norm: {np.linalg.norm(a_lc):.4f}")
    
    # Rollout both
    h_zero = np.zeros(64)
    
    traj_pf = rollout_flow(pf, np.zeros(16), h_zero, wm, n_steps=10)
    traj_lc = rollout_flow(lc, np.zeros(16) + 0.5, h_zero, wm, n_steps=10)
    
    print(f"\n  PointFlow final dist from target: "
          f"{np.linalg.norm(traj_pf['final_state'] - pf.z_target):.4f}")
    print(f"  LimitCycle final state norm: "
          f"{np.linalg.norm(traj_lc['final_state']):.4f}")
    
    # Composed flow
    cf = ComposedFlow([pf, lc], weights=[0.5, 0.5])
    a_cf = cf.compute_action(z, h)
    print(f"\n  ComposedFlow action norm: {np.linalg.norm(a_cf):.4f}")
    print(f"  (should be ~0.5 * point + 0.5 * cycle)")
    
    print("\n  ✓ All flow types operational")


def test_flow_manifold():
    """Test flow manifold organization."""
    print("\n" + "=" * 60)
    print("FLOW MANIFOLD TEST")
    print("=" * 60)
    
    wm = MinimalWorldModel(event_dim=32, latent_dim=16, belief_dim=64, action_dim=16)
    manifold = FlowManifold(flow_dim=4)
    
    # Add diverse flows
    for i in range(6):
        if i % 2 == 0:
            target = np.random.randn(16) * 0.5
            flow = PointFlow(target, gain=0.5)
        else:
            center = np.random.randn(16) * 0.3
            flow = LimitCycleFlow(center, radius=1.0, omega=0.5)
        manifold.add_flow(flow, f'flow_{i}')
    
    # Test interpolation
    coord = np.zeros(4)
    blended = manifold.interpolate_at(coord, wm, np.zeros(16))
    
    print(f"\n  Blended flow type: {blended.flow_type.value}")
    print(f"  Sub-flows: {len(blended.flows)}")
    print(f"  Weights: {[f'{w:.2f}' for w in blended.weights]}")
    
    # Test similarity
    if len(manifold.flows) >= 2:
        sim = manifold.compute_similarity(
            'flow_0', 'flow_1', wm, np.zeros(16), n_steps=5
        )
        print(f"\n  Similarity flow_0 ↔ flow_1: {sim:.4f}")
    
    # Test topology organization
    manifold.organize_topology(wm, np.zeros(16), n_steps=5)
    print(f"\n  Topology organized: {len(manifold.flow_coords)} coordinates")
    
    # Check coords changed
    coord_changes = [np.linalg.norm(c) for c in manifold.flow_coords.values()]
    print(f"  Coord norms: min={min(coord_changes):.2f}, max={max(coord_changes):.2f}")
    
    print("\n  ✓ Flow manifold operational")


def test_flow_cem():
    """Test CEM planning over flow manifold."""
    print("\n" + "=" * 60)
    print("FLOW CEM TEST")
    print("=" * 60)
    
    wm = MinimalWorldModel(event_dim=32, latent_dim=16, belief_dim=64, action_dim=16)
    manifold = FlowManifold(flow_dim=4)
    
    for i in range(8):
        target = np.random.randn(16) * random.uniform(-1, 1) * 0.5
        flow = PointFlow(target, gain=random.uniform(0.2, 0.8))
        manifold.add_flow(flow, f'flow_{i}')
    
    adapter = SkillDynamicsAdapter(wm)
    evaluator = ProbabilisticGoalEvaluator(wm)
    
    goal = GoalAttractor(
        goal_id='cem_goal',
        attractor_state=np.ones(16) * 2.0,
        basin_radius=2.0,
        priority=0.9,
        decay_rate=0.01,
        success_criteria={'type': 'achievable'}
    )
    
    cem = FlowCEM(
        world_model=wm,
        manifold=manifold,
        evaluator=evaluator,
        flow_dim=4,
        n_candidates=30,
        n_elites=6,
        n_iterations=3
    )
    
    plan = cem.plan_flow(np.zeros(16), np.zeros(64), goal)
    
    print(f"\n  Plan score: {plan['score']:.4f}")
    print(f"  Coord norm: {np.linalg.norm(plan['coord']):.4f}")
    print(f"  Has flow: {plan['flow'] is not None}")
    
    if plan['flow']:
        print(f"  Flow type: {plan['flow'].flow_type.value}")
        print(f"  Sub-flows: {len(plan['flow'].flows)}")
    
    print("\n  ✓ Flow CEM operational")


def test_full_dynamical_execution():
    """Test full dynamical execution."""
    print("\n" + "=" * 60)
    print("FULL DYNAMICAL EXECUTION TEST")
    print("=" * 60)
    
    wm = MinimalWorldModel(event_dim=32, latent_dim=16, belief_dim=64, action_dim=16)
    
    goal = GoalAttractor(
        goal_id='flow_goal',
        attractor_state=np.ones(16) * 1.5,
        basin_radius=2.0,
        priority=0.9,
        decay_rate=0.01,
        success_criteria={'type': 'achievable'}
    )
    
    engine = DynamicalSkillEngine(
        world_model=wm,
        goal=goal,
        n_initial_flows=8,
        flow_dim=4
    )
    
    result = engine.execute_goal(np.zeros(16), max_steps=20)
    
    print(f"\n  Goal reached: {result['goal_reached']}")
    print(f"  Steps: {result['n_steps']}")
    print(f"  Flows: {result['n_flows']}")
    
    ft = result['flow_types']
    print(f"  Flow types: {ft}")
    
    stab = result['stability']
    print(f"  Stability: mean={stab['mean']:.4f}, max={stab['max']:.4f}")
    
    if result['execution_log']:
        print("\n  Last 3 steps:")
        for entry in result['execution_log'][-3:]:
            print(f"    goal_prob={entry['goal_prob']:.3f}, "
                  f"flow={entry['flow_id']}, "
                  f"type={entry['flow_type']}, "
                  f"stability={entry['stability']:.3f}")
    
    print("\n  ✓ Dynamical execution operational")


def test_flow_comparison():
    """Compare point attractor vs limit cycle dynamics."""
    print("\n" + "=" * 60)
    print("FLOW COMPARISON: Point vs Limit Cycle")
    print("=" * 60)
    
    wm = MinimalWorldModel(event_dim=32, latent_dim=16, belief_dim=64, action_dim=16)
    h = np.zeros(64)
    
    # Point flow: converge to target
    target = np.ones(16) * 0.5
    pf = PointFlow(target, gain=0.5)
    traj_pf = rollout_flow(pf, np.zeros(16), h, wm, n_steps=20)
    
    pf_distances = [
        np.linalg.norm(traj_pf['states'][t] - target)
        for t in range(len(traj_pf['states']))
    ]
    
    print(f"\n  PointFlow:")
    print(f"    Initial dist to target: {pf_distances[0]:.4f}")
    print(f"    Final dist to target: {pf_distances[-1]:.4f}")
    print(f"    Converged: {pf_distances[-1] < pf_distances[0] * 0.1}")
    
    # Limit cycle: oscillate around center
    center = np.zeros(16)
    lc = LimitCycleFlow(center, radius=1.0, omega=0.8, K_radial=0.5)
    traj_lc = rollout_flow(lc, np.zeros(16) + 0.5, h, wm, n_steps=20)
    
    lc_distances = [
        np.linalg.norm(traj_lc['states'][t] - center)
        for t in range(len(traj_lc['states']))
    ]
    
    print(f"\n  LimitCycle:")
    print(f"    Initial dist to center: {lc_distances[0]:.4f}")
    print(f"    Final dist to center: {lc_distances[-1]:.4f}")
    print(f"    Near radius 1.0: {abs(lc_distances[-1] - 1.0) < 0.3}")
    
    # Lyapunov estimates
    pf_stab = pf.compute_lyapunov_estimate()
    lc_stab = lc.compute_lyapunov_estimate()
    
    print(f"\n  Stability:")
    print(f"    PointFlow Lyapunov estimate: {pf_stab:.4f} (should be high - convergent)")
    print(f"    LimitCycle Lyapunov estimate: {lc_stab:.4f} (should be lower - oscillatory)")
    
    print("\n  ✓ Flow comparison complete")


if __name__ == "__main__":
    test_flow_types()
    test_flow_manifold()
    test_flow_cem()
    test_full_dynamical_execution()
    test_flow_comparison()
    
    print("\n" + "=" * 60)
    print("PHASE 35: DYNAMICAL SKILL FLOWS")
    print("=" * 60)
    
    print("""
KEY SHIFT FROM PHASE 34:
  BEFORE: a = attractor_point  (static action, state-independent)
  AFTER:  a_t = π_skill(z_t, h_t)  (flow policy, state-dependent)

WHAT CHANGED:
  1. PointFlow — linear attractor: a = K * (z_target - z)
  2. LimitCycleFlow — stable oscillation: ω*R*z + K*(r - |z-c|)*(z-c)
  3. LinearFlow — general linear dynamics: a = A @ z + b
  4. ComposedFlow — superposition: a = Σ w_i * π_i(z, h)
  5. FlowManifold — interpolates flow BEHAVIOR, not actions
  6. FlowCEM — plans over flow parameter space
  7. Flow similarity — trajectory-based, not action-based
  8. Topology organization — similar dynamics → close on manifold

ARCHITECTURAL PROGRESSION:
  Phase 33: point attractor (static action, wrong space)
  Phase 34: inverse dynamics (action space stabilization)
  Phase 35: dynamical flows (state-dependent policies)

NEXT (Phase 36):
  Execution-Consistent World Model Training
  Now TRAJECTORIES have structure (from persistent flows),
  so world model training becomes meaningful.
""")
